name: GitHub Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and test
        run: |
          gradle build
          gradle test

      - name: Publish artifacts
        run: ./gradlew publish

      - name: Deploy to staging
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh staging
      - name: Deploy to production
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh production

      - name: Deploy to production
        # Add deployment logic here
